version: 2.1

executors:
  moneta-runner-executor:
    machine: true
    resource_class: moneta-labs/moneta-runner   

parameters:
  ENVIRONMENT:
    description: "Specifies the deployment environment: dev, stage, or prod."
    type: string
    default: ""

jobs:
  Hold_for_approval:
    type: approval  

  Building_App:
    machine: true
    resource_class: moneta-labs/moneta-runner
    parameters:
      ENVIRONMENT:
        type: string
    steps:
      - run:
          name: Extract and Print ENVIRONMENT value
          command: |
            echo "Extracted ENVIRONMENT value: << parameters.ENVIRONMENT >>"
            echo "export ENVIRONMENT=<< parameters.ENVIRONMENT >>" >> $BASH_ENV
      - checkout
      - run:
          name: Authenticate with GCP
          command: |
            echo "$GCLOUD_SERVICE_KEY" > ./service-account.json
            SERVICE_PROJECT_ID="${Name_Prefix}<< parameters.ENVIRONMENT >>"
            echo 'export GOOGLE_APPLICATION_CREDENTIALS=./service-account.json' >> $BASH_ENV
            gcloud auth activate-service-account --key-file=./service-account.json
            gcloud --quiet config set project "$SERVICE_PROJECT_ID"
      - run:
          name: Set Short Commit SHA
          command: |
            export TAG_ID=${CIRCLE_SHA1:0:8}
            echo "export TAG_ID=${TAG_ID}" >> $BASH_ENV
            echo "Generated TAG_ID: $TAG_ID"
            echo $TAG_ID > /tmp/TAG_ID.txt
      - run:
          name: Building & Pushing Docker Image
          command: |
            gcloud secrets versions access latest --project="${Name_Prefix}<< parameters.ENVIRONMENT >>" --secret="${Name_Prefix}<< parameters.ENVIRONMENT >>-python-service" >> .env
            rm -f ./service-account.json
            docker build --platform=linux/amd64 --pull -t "$GCP_REGION-docker.pkg.dev/${Name_Prefix}<< parameters.ENVIRONMENT >>/${Name_Prefix}-python-service/${Name_Prefix}-python-service:$TAG_ID" -f Dockerfile .
            gcloud auth configure-docker "$GCP_REGION-docker.pkg.dev" --quiet > /dev/null 2>&1
            docker push "$GCP_REGION-docker.pkg.dev/${Name_Prefix}<< parameters.ENVIRONMENT >>/${Name_Prefix}-python-service/${Name_Prefix}-python-service:$TAG_ID"
      - persist_to_workspace:
          root: /tmp
          paths:
            - TAG_ID.txt

  Deploying_App:
    machine: true
    resource_class: moneta-labs/moneta-runner
    parameters:
      ENVIRONMENT:
        type: string
    steps:
      - run:
          name: Extract and Print ENVIRONMENT value
          command: |
            echo "Extracted ENVIRONMENT value: << parameters.ENVIRONMENT >>"
            echo "export ENVIRONMENT=<< parameters.ENVIRONMENT >>" >> $BASH_ENV
      - attach_workspace:
          at: /tmp
      - checkout
      - run:
          name: Authenticate with GCP
          command: |
            echo "$GCLOUD_SERVICE_KEY" > ./service-account.json
            SERVICE_PROJECT_ID="${Name_Prefix}<< parameters.ENVIRONMENT >>"
            echo 'export GOOGLE_APPLICATION_CREDENTIALS=./service-account.json' >> $BASH_ENV
            gcloud auth activate-service-account --key-file=./service-account.json
            gcloud --quiet config set project "$SERVICE_PROJECT_ID"
      - run:
          name: Fetch TAG_ID
          command: |
            export TAG_ID=$(cat /tmp/TAG_ID.txt)
            echo "Using TAG_ID: $TAG_ID"
            echo "export TAG_ID=${TAG_ID}" >> $BASH_ENV
      - run:
          name: Deploying the Application
          command: |
            bash .circleci/deploy.sh $TAG_ID
workflows:
  Moneta-PYTHON-SERVICE-PROD:
    when:
      and:
        - not:
            equal: ["", << pipeline.parameters.ENVIRONMENT >>]
        - equal: ["prod", << pipeline.parameters.ENVIRONMENT >>]
    jobs:
      - Building_App:
          ENVIRONMENT: << pipeline.parameters.ENVIRONMENT >>
          filters:
            branches:
              only: main

      - Hold_for_approval:
          requires:
            - Building_App

      - Deploying_App:
          ENVIRONMENT: << pipeline.parameters.ENVIRONMENT >>
          requires:
            - Hold_for_approval
          filters:
            branches:
              only: main

  Moneta-PYTHON-SERVICE-NON-PROD:
    when:
      and:
        - not:
            equal: ["", << pipeline.parameters.ENVIRONMENT >>]
        - not:
            equal: ["prod", << pipeline.parameters.ENVIRONMENT >>]
    jobs:
      - Building_App:
          ENVIRONMENT: << pipeline.parameters.ENVIRONMENT >>
          filters:
            branches:
              only: main

      - Deploying_App:
          ENVIRONMENT: << pipeline.parameters.ENVIRONMENT >>
          requires:
            - Building_App
          filters:
            branches:
              only: main
