version: 2.1

parameters:
  run_manually:
    type: boolean
    default: false

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

workflows:
  say-hello-workflow:
    when: << pipeline.parameters.run_manually >>
    jobs:
      - say-hello
